spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: 
              -GET
              -POST
              -PUT
              -DELETE
                      
      routes:
        - id: admin
          uri: http://localhost:8083/
          predicates:
            - Path=/Admin/**
        - id: bookingorder
          uri: http://localhost:8081/
          predicates:
            - Path=/booki/**

server:
  port: 20003





